version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress/themes:/var/www/html/wp-content/themes/
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DEBUG: 1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - '3000:80'

volumes:
  wordpress:
  db: